//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tnguyen_Resume.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project
    {
        public System.Guid ID { get; set; }
        public string ProjectImage { get; set; }
        public string ProjectTitle { get; set; }
        public string ProjectInfo { get; set; }
        public string ProjectDetail { get; set; }
        public string ProjectJob { get; set; }
        public string ProjectURL { get; set; }
        public Nullable<System.DateTime> ProjectTime { get; set; }
        public Nullable<System.Guid> ID_User { get; set; }
    }
}
