//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tnguyen_Resume.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Testimonial
    {
        public int ID { get; set; }
        public string TestimonialsInfo { get; set; }
        public string TestimonialsAuthor { get; set; }
        public Nullable<int> ID_User { get; set; }
    
        public virtual Information Information { get; set; }
    }
}
