//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tnguyen_Resume.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Work
    {
        public System.Guid ID { get; set; }
        public string WorksTitle { get; set; }
        public string WorksInfo { get; set; }
        public Nullable<System.DateTime> WorksDate { get; set; }
        public string WorksDetail { get; set; }
        public Nullable<System.Guid> ID_User { get; set; }
    }
}
